sudo: required
dist: trusty

os:
- osx
- linux

env:
- NODE_ENV=dev
- NODE_ENV=prod


language: node_js

node_js:
  - 8

cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

language: node_js

# Enable when https://github.com/yarnpkg/yarn/issues/1233 and
# https://github.com/yarnpkg/yarn/issues/1059 are resolved and disable npm cache
#
# cache:
#   directories:
#   - $HOME/.yarn-cache

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - icnsutils
    - graphicsmagick
    - xz-utils
    - xorriso

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start &
  - sleep 3

script:
  # - yarn run lint
  - yarn run build
  - yarn run test
  - if [[ "$NODE_ENV" == "dev" ]]; then yarn run test-e2e; fi
  - yarn run package
